
##  Loading Libraries & Dataset
#

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
    
from IPython.display import display  # print() can only print text , for tabular multiple tabular 
                                     # dataframes to print in a single cell we use display()

import warnings 
warnings.filterwarnings('ignore') # as some functions maybe depricated in future versions to ignore the 
                                  # messages of these updates we ignore them}

In [2]:
df = pd.read_csv('../data/01_cleaned_heart_data.csv')
display(df.head())

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140.0,289.0,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160.0,180.0,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130.0,283.0,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138.0,214.0,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150.0,195.0,0,Normal,122,N,0.0,Up,0

#
## 3) Data Preprocessing
#

##
### 3.1 - Label Encoding Binary Categorical Variables
##

- ML Algorithms cannot understand and handle text like ATA / Normal / M / F 
- We need to encode them to numbers 
- For Binary Categories ( 2 values like Male/Female) , we encode them to 0/1 manaully ..

In [3]:
categorical_df = df.select_dtypes(include = 'object')
display(categorical_df.head(1))

categorical_columns = categorical_df.columns
display(categorical_df.columns)

  Sex ChestPainType RestingECG ExerciseAngina ST_Slope
0   M           ATA     Normal              N       Up

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

- Above are the categorical Columns of the dataset

In [4]:
for col in categorical_columns : 
    unique_count  = df[col].nunique()   # df['col_name'].nunique() gives us total number of unique values in column
    unique_values = df[col].unique()    # df['col_name'].unique() gives us list of unique values of required column
    print(f"Column : {col:<20} | Unique Count: {unique_count:<12} | Values: {unique_values}")

Column : Sex                  | Unique Count: 2            | Values: ['M' 'F']
Column : ChestPainType        | Unique Count: 4            | Values: ['ATA' 'NAP' 'ASY' 'TA']
Column : RestingECG           | Unique Count: 3            | Values: ['Normal' 'ST' 'LVH']
Column : ExerciseAngina       | Unique Count: 2            | Values: ['N' 'Y']
Column : ST_Slope             | Unique Count: 3            | Values: ['Up' 'Flat' 'Down']

##### Binary Categorical Columnns     :  Sex / ExerciseAngina
##### Multi-Class Categorical Columns :  ChestPainType / RestingECG / ST_Slope

In [5]:
sex_mapping = {
    'M': 1 ,
    'F': 0 
}
df['Sex'] = df['Sex'].map(sex_mapping)

angina_mapping = {
    'Y': 1 , 
    'N': 0
}
df['ExerciseAngina'] = df['ExerciseAngina'].map(angina_mapping)

In [6]:
display(df.head())
display(df[['Sex', 'ExerciseAngina']].info())

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,ATA,140.0,289.0,0,Normal,172,0,0.0,Up,0
1,49,0,NAP,160.0,180.0,0,Normal,156,0,1.0,Flat,1
2,37,1,ATA,130.0,283.0,0,ST,98,0,0.0,Up,0
3,48,0,ASY,138.0,214.0,0,Normal,108,1,1.5,Flat,1
4,54,1,NAP,150.0,195.0,0,Normal,122,0,0.0,Up,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sex             918 non-null    int64
 1   ExerciseAngina  918 non-null    int64
dtypes: int64(2)
memory usage: 14.5 KB

None

- We can verify here binary categorical variables are encoded to 0/1 Integers

##
### 3.1 - One Hot Encoding Multi-Class Categorical Variables
##

##### Why can't we label encode multi-class Categorical Variables
- We can label encode multi-class variables as 0/1/2/3..
- If we encode ATA=0, NAP=1, ASY=2, TA=3, the algorithm thinks ASY is greater than  ATA which is mathematically meaningless -  there should be no ordinal relationship between chest pain types..

In [7]:
for col in categorical_columns : 
    unique_count  = df[col].nunique()   # df['col_name'].nunique() gives us total number of unique values in column
    unique_values = df[col].unique()    # df['col_name'].unique() gives us list of unique values of required column
    print(f"Column : {col:<20} | Unique Count: {unique_count:<12} | Values: {unique_values}")

Column : Sex                  | Unique Count: 2            | Values: [1 0]
Column : ChestPainType        | Unique Count: 4            | Values: ['ATA' 'NAP' 'ASY' 'TA']
Column : RestingECG           | Unique Count: 3            | Values: ['Normal' 'ST' 'LVH']
Column : ExerciseAngina       | Unique Count: 2            | Values: [0 1]
Column : ST_Slope             | Unique Count: 3            | Values: ['Up' 'Flat' 'Down']

##### Multi-Class Categorical Columns :  ChestPainType / RestingECG / ST_Slope

In [8]:
df = pd.get_dummies(df, columns=['ChestPainType', 'RestingECG', 'ST_Slope'], drop_first=True)

In [9]:
# We need to convert Ture/False to 1/0 (numbers) , we do this by multiplying dataframe with 1..
df = df*1

In [10]:
df.head(1)
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                918 non-null    int64
 1   Sex                918 non-null    int64
 2   RestingBP          918 non-null    float64
 3   Cholesterol        918 non-null    float64
 4   FastingBS          918 non-null    int64
 5   MaxHR              918 non-null    int64
 6   ExerciseAngina     918 non-null    int64
 7   Oldpeak            918 non-null    float64
 8   HeartDisease       918 non-null    int64
 9   ChestPainType_ATA  918 non-null    int64
 10  ChestPainType_NAP  918 non-null    int64
 11  ChestPainType_TA   918 non-null    int64
 12  RestingECG_Normal  918 non-null    int64
 13  RestingECG_ST      918 non-null    int64
 14  ST_Slope_Flat      918 non-null    int64
 15  ST_Slope_Up        918 non-null    int64
dtypes: float64(3), int64(13)
memory usage: 114.9 KB

None

#### Dummy Variable Trap (Multi-Collinearity): 

- If we look at a patient and see they have 0 for ATA, 0 for NAP, and 0 for TA ,  We already know with 100% certainty that they must be ASY ChestPain Type. So we don't actually need ASY Column which means ASY Column is " Redundant"
  
- If we feed Redundant Data into an algoritm , we cause a mathematical crash called  "Multicollinearity"

- That's why we use drop_first = True while calling pd.get_dummies() so redundant column is dropped while executing this function

- Verified dataypes of newly created columns by one-hot-encoding of multi-class categorical variable columns as integer
- Verified avoiding dummy variable trap (adding redundant column)
- Verified datatypes of newly creatd columns by label encoding of binary categorical variable columns

##
### 3.2 - Data Splitting :  Training & Testing Data
##

####

#### Separate The Features (X) from Target Variable (Y)

- X = Patient's entire medical record including encoded columns ( Age ,  FastingBS , MaxHR , Cholesterol etc. )
- Y = HeartDisease (0/1)

In [16]:
display(df.head())

# Capital X because its a 2D dataframe with rows and columns 
X = df.drop(columns = ['HeartDisease'])
display(X.head(1))

# Lowercase y beacuse its a series with 0/1 for HeartDisease 
y = df['HeartDisease']
display(y)

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,40,1,140.0,289.0,0,172,0,0.0,0,1,0,0,1,0,0,1
1,49,0,160.0,180.0,0,156,0,1.0,1,0,1,0,1,0,1,0
2,37,1,130.0,283.0,0,98,0,0.0,0,1,0,0,0,1,0,1
3,48,0,138.0,214.0,0,108,1,1.5,1,0,0,0,1,0,1,0
4,54,1,150.0,195.0,0,122,0,0.0,0,0,1,0,1,0,0,1

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,40,1,140.0,289.0,0,172,0,0.0,1,0,0,1,0,0,1

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64